'use server';
/**
 * @fileOverview This file defines a Genkit flow for providing personalized health tips based on daily log data and wellness goals, using AI.
 *
 * - getPersonalizedHealthTips - A function that generates personalized health tips.
 * - GetPersonalizedHealthTipsInput - The input type for the getPersonalizedHealthTips function.
 * - GetPersonalizedHealthTipsOutput - The return type for the getPersonalizedHealthTips function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GetPersonalizedHealthTipsInputSchema = z.object({
  sleepHours: z.number().describe('The number of hours of sleep the user got.'),
  waterIntake: z.number().describe('The amount of water the user drank in glasses.'),
  mood: z.enum(['happy', 'neutral', 'sad', 'stressed']).describe('The user\'s mood.'),
  wellnessGoal: z.string().describe('The user\'s wellness goal.'),
  meals: z.string().describe('The meals the user ate today.'),
  steps: z.number().describe('The number of steps the user took today.'),
});

export type GetPersonalizedHealthTipsInput = z.infer<typeof GetPersonalizedHealthTipsInputSchema>;

const GetPersonalizedHealthTipsOutputSchema = z.object({
  healthTip: z.string().describe('A personalized health tip generated by AI.'),
});

export type GetPersonalizedHealthTipsOutput = z.infer<typeof GetPersonalizedHealthTipsOutputSchema>;

export async function getPersonalizedHealthTips(
  input: GetPersonalizedHealthTipsInput
): Promise<GetPersonalizedHealthTipsOutput> {
  return getPersonalizedHealthTipsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'getPersonalizedHealthTipsPrompt',
  input: {schema: GetPersonalizedHealthTipsInputSchema},
  output: {schema: GetPersonalizedHealthTipsOutputSchema},
  prompt: `You are a wellness assistant providing personalized health tips based on the user\'s daily log data and wellness goals.

  Wellness Goal: {{{wellnessGoal}}}
  Sleep Hours: {{{sleepHours}}}
  Water Intake: {{{waterIntake}}}
  Mood: {{{mood}}}
  Meals: {{{meals}}}
  Steps: {{{steps}}}

  Provide a concise and specific health tip to help the user improve their overall well-being, taking into account all the provided information.
  Consider suggesting tips related to sleep, hydration, mood improvement, diet, and exercise.
  Be conversational, and include Urdu phrases like "Aaj ki health tip" to introduce wellness tips.
  `,
});

const getPersonalizedHealthTipsFlow = ai.defineFlow(
  {
    name: 'getPersonalizedHealthTipsFlow',
    inputSchema: GetPersonalizedHealthTipsInputSchema,
    outputSchema: GetPersonalizedHealthTipsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
